# config/_default/languages.en.toml

title = "cookies-xor-cream"

[author]
name = "cookies-xor-cream"
image = "img/cookie.png"
headline = "A list of my ramblings, if anyone would like to indulge me."
bio = "A software developer who sometimes jots down a few lines of something cringe on their daily transit."
links = [
  { github = "https://github.com/cookies-xor-cream" }
]

[permalinks]
  posts = "poems/:title"