enableSearch = true

colorScheme = "fire"
defaultAppearance = "dark"

homepage.layout = "profile"

header.layout = "fixed-fill"

footer.showScrollToTop = false
footer.showAppearanceSwitcher = true

article.showReadingTime = false

# Theme Choices #
# ------------- #
# Blowfish (default) #
# Avocado #
# Fire #
# Forest #
# Princess #
# Neon #
# Bloody #
# Terminal #
# Marvel #
# Noir #
# Autumn #
# Congo #
# Slate #
